server:
  port: 8091

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
      fail-on-invalid-subtype: false
      fail-on-null-for-primitives: false
    default-property-inclusion: non_null
  profiles:
    active: 1

logging:
  file:
    name: logs/rentey-service.log
  level:
    root: INFO
    com: DEBUG  # To see DEBUG logs from your packages
    org.springframework.web: INFO
    org.springframework.boot: INFO

authorization:
  service:
    base-url: http://localhost:8088
    response-timeout-seconds: 120
    connect-timeout-millis: 100000
    credentials:
      userNameOrEmailAddress: "ejaradmin"
      password: "123456"
      rememberClient: false

csv:
  import:
    directory: rentey-service/customersToImport
  export:
    directory: rentey-service/importResults


