server:
  port: 8090
  max-http-header-size: 10MB

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
      fail-on-invalid-subtype: false
      fail-on-null-for-primitives: false
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB

rentey:
  service:
    base-url: http://localhost:8089
    api:
      base-path: /api/services/app

